name: hello-world
on:
  push:
    branches:
      - main
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run main.js
        run: node main.js
